//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipehub
{


    public partial class Add_Product
    {
        protected global::System.Web.UI.WebControls.TextBox ProdName;

        protected global::System.Web.UI.WebControls.TextBox ProdDescrip;

        protected global::System.Web.UI.WebControls.TextBox ProdPrice;

        protected global::System.Web.UI.WebControls.FileUpload ImgUpload;
    }
}
