//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipehub
{


    public partial class Add_Recipe
    {
        protected global::System.Web.UI.WebControls.TextBox RecVideo;

        protected global::System.Web.UI.WebControls.TextBox RecIngred;

        protected global::System.Web.UI.WebControls.TextBox RecMethod;

        protected global::System.Web.UI.WebControls.TextBox RecTime;

        protected global::System.Web.UI.WebControls.TextBox RecCost;

        protected global::System.Web.UI.WebControls.FileUpload ImgUpload;

    }
}
